#!/usr/bin/env bun
/**
 * Writes the current git HEAD hash to version.generated.ts.
 * Run before start (e.g. in prestart or manually) so the bot has a version without calling git at runtime.
 */

import { spawnSync } from "bun";
import { writeFileSync } from "fs";
import { join } from "path";

const DM_BOT_DIR = import.meta.dir ?? process.cwd();
const REPO_ROOT = join(DM_BOT_DIR, "..");
const OUT_FILE = join(DM_BOT_DIR, "version.generated.ts");

const proc = spawnSync(["git", "rev-parse", "HEAD"], { stdout: "pipe", stderr: "pipe", cwd: REPO_ROOT });
const hash = proc.stdout?.toString().trim() ?? "unknown";

const content = `/** Generated by write-version.ts — do not edit. Git hash of the dm-bot project. */
export const VERSION = "${hash}";
`;

writeFileSync(OUT_FILE, content, "utf8");
console.log("[write-version] VERSION =", hash);
