// ---------------------------------------------------------------------------
// scripts/generate-tools.ts — Generate .opencode/tools/{alias}.ts and
//                             update AGENTS.md from plugins.json
//
// Usage: bun run scripts/generate-tools.ts
// ---------------------------------------------------------------------------

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

const ROOT = join(import.meta.dir, '..');
const PLUGINS_JSON = join(ROOT, 'plugins.json');
const TOOLS_DIR = join(ROOT, '.opencode', 'tools');
const AGENTS_MD = join(ROOT, 'AGENTS.md');

// ---------------------------------------------------------------------------
// Read plugins.json
// ---------------------------------------------------------------------------

type PluginEntry = {
  alias: string;
  repo: string;
  version: string;
  opencode?: string;
};

type PluginsJson = {
  plugins: PluginEntry[];
};

const pluginsJson = JSON.parse(readFileSync(PLUGINS_JSON, 'utf8')) as PluginsJson;

if (!existsSync(TOOLS_DIR)) {
  mkdirSync(TOOLS_DIR, { recursive: true });
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function pluginNameFromRepo(repo: string): string {
  return repo.split('/').at(-1) ?? repo;
}

function replaceAgentBlock(content: string, pluginName: string, block: string): string {
  const start = `<!-- plugin:${pluginName} -->`;
  const end = `<!-- /plugin:${pluginName} -->`;
  const tagged = `${start}\n${block.trim()}\n${end}`;

  if (content.includes(start)) {
    // Replace existing block
    const re = new RegExp(`${start}[\\s\\S]*?${end}`, 'g');

    return content.replace(re, tagged);
  }

  // Append new block
  return content.trimEnd() + '\n\n' + tagged + '\n';
}

// ---------------------------------------------------------------------------
// Process each plugin
// ---------------------------------------------------------------------------

for (const entry of pluginsJson.plugins) {
  const { alias, repo } = entry;
  const pluginName = alias ?? pluginNameFromRepo(repo);

  const opencodePath = entry.opencode
    ? join(ROOT, entry.opencode)
    : join(ROOT, 'plugins', pluginName, 'opencode.ts');

  if (!existsSync(opencodePath)) {
    console.warn(
      `[generate-tools] Skipping ${pluginName}: no opencode.ts found at ${opencodePath}`,
    );

    continue;
  }

  // Import plugin's exports
  const mod = (await import(opencodePath)) as {
    createToolDefinitions: (pluginName: string) => ReadonlyArray<{ name: string }>;
    agentInstructions?: (pluginName: string) => string;
  };

  if (!mod.createToolDefinitions) {
    console.warn(`[generate-tools] Skipping ${pluginName}: no createToolDefinitions export`);
    continue;
  }

  const defs = mod.createToolDefinitions(pluginName);
  const relPath = `../../plugins/${pluginName}/opencode`;

  // Generate named exports — just def.name, opencode prefixes filename automatically
  const exports = defs.map((def, i) => `export const ${def.name} = tool(defs[${i}]);`).join('\n');

  const toolFile = `\
// ---------------------------------------------------------------------------
// .opencode/tools/${pluginName}.ts — AUTO-GENERATED, do not edit
// Generated by: bun run scripts/generate-tools.ts
// Source: plugins/${pluginName}/opencode.ts
// ---------------------------------------------------------------------------

import { tool } from '@opencode-ai/plugin';
import { createToolDefinitions } from '${relPath}';

const defs = createToolDefinitions('${pluginName}');

${exports}
`;

  const toolPath = join(TOOLS_DIR, `${pluginName}.ts`);
  writeFileSync(toolPath, toolFile, 'utf8');
  console.log(`[generate-tools] Generated ${toolPath.replace(ROOT + '/', '')}`);

  // Update AGENTS.md
  if (mod.agentInstructions) {
    const instructions = mod.agentInstructions(pluginName);
    const existing = existsSync(AGENTS_MD) ? readFileSync(AGENTS_MD, 'utf8') : '';
    const updated = replaceAgentBlock(existing, pluginName, instructions);
    writeFileSync(AGENTS_MD, updated, 'utf8');
    console.log(`[generate-tools] Updated AGENTS.md for ${pluginName}`);
  }
}

console.log('[generate-tools] Done.');
