// ---------------------------------------------------------------------------
// scripts/generate-tools.ts — Generate .opencode/tools/{alias}.ts,
//                             TOOLS.md (plugin instructions), and
//                             generated/plugins.ts
//
// Usage: bun run scripts/generate-tools.ts
// Idempotent: TOOLS.md is recreated each run. AGENTS.md is not modified;
// add a manual "See [TOOLS.md](TOOLS.md)" section there if desired.
// ---------------------------------------------------------------------------

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

const ROOT = join(import.meta.dir, '..');
const PLUGINS_JSON = join(ROOT, 'plugins.json');
const TOOLS_DIR = join(ROOT, '.opencode', 'tools');
const TOOLS_MD = join(ROOT, 'TOOLS.md');

// ---------------------------------------------------------------------------
// Read plugins.json
// ---------------------------------------------------------------------------

type PluginEntry = {
  alias: string;
  repo: string;
  version: string;
  opencode?: string;
};

type PluginsJson = {
  plugins: PluginEntry[];
};

const pluginsJson = JSON.parse(readFileSync(PLUGINS_JSON, 'utf8')) as PluginsJson;

if (!existsSync(TOOLS_DIR)) {
  mkdirSync(TOOLS_DIR, { recursive: true });
}

const pluginInstructions: { alias: string; instructions: string }[] = [];

// ---------------------------------------------------------------------------
// Process each plugin
// ---------------------------------------------------------------------------

for (const entry of pluginsJson.plugins) {
  const { alias } = entry;

  const opencodePath = entry.opencode
    ? join(ROOT, entry.opencode)
    : join(ROOT, 'plugins', alias, 'opencode.ts');

  if (!existsSync(opencodePath)) {
    console.warn(`[generate-tools] Skipping ${alias}: no opencode.ts found at ${opencodePath}`);
    continue;
  }

  // Import plugin's exports
  const mod = (await import(opencodePath)) as {
    createToolDefinitions: (alias: string) => ReadonlyArray<{ name: string }>;
    agentInstructions?: (alias: string) => string;
  };

  if (!mod.createToolDefinitions) {
    console.warn(`[generate-tools] Skipping ${alias}: no createToolDefinitions export`);
    continue;
  }

  const defs = mod.createToolDefinitions(alias);
  const relPath = `../../plugins/${alias}/opencode`;

  // Generate named exports — just def.name, opencode prefixes filename automatically
  const exports = defs.map((def, i) => `export const _${def.name} = tool(defs[${i}]);`).join('\n');

  const toolFile = `\
// ---------------------------------------------------------------------------
// .opencode/tools/${alias}.ts — AUTO-GENERATED, do not edit
// Generated by: bun run scripts/generate-tools.ts
// Source: plugins/${alias}/opencode.ts
// ---------------------------------------------------------------------------

import { tool } from '@opencode-ai/plugin';
import { createToolDefinitions } from '${relPath}';

const defs = createToolDefinitions('${alias}');

${exports}
`;

  const toolPath = join(TOOLS_DIR, `${alias}.ts`);
  writeFileSync(toolPath, toolFile, 'utf8');
  console.log(`[generate-tools] Generated ${toolPath.replace(ROOT + '/', '')}`);

  if (mod.agentInstructions) {
    pluginInstructions.push({ alias, instructions: mod.agentInstructions(alias) });
  }
}

// ---------------------------------------------------------------------------
// Write TOOLS.md (recreated each run)
// ---------------------------------------------------------------------------

const toolsMdSections = pluginInstructions
  .map(({ alias, instructions }) => `## Plugin: ${alias}\n\n${instructions.trim()}\n`)
  .join('\n');

writeFileSync(
  TOOLS_MD,
  `# Plugin tool instructions

This file is auto-generated by \`bun run scripts/generate-tools.ts\`. Do not edit.

${toolsMdSections}`.trimEnd() + '\n',
  'utf8',
);

console.log('[generate-tools] Wrote TOOLS.md');

// ---------------------------------------------------------------------------
// Generate generated/plugins.ts
// ---------------------------------------------------------------------------

const GENERATED_DIR = join(ROOT, 'generated');
const PLUGINS_TS = join(GENERATED_DIR, 'plugins.ts');

if (!existsSync(GENERATED_DIR)) {
  mkdirSync(GENERATED_DIR, { recursive: true });
}

function toPluginExportName(alias: string): string {
  // todo → TodoPlugin, job-scheduler → JobSchedulerPlugin
  const pascal = alias
    .split('-')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');

  return `${pascal}Plugin`;
}

const imports = pluginsJson.plugins
  .map((entry) => {
    const exportName = toPluginExportName(entry.alias);

    return `import { ${exportName} } from '../plugins/${entry.alias}/init';`;
  })
  .join('\n');

const registrations = pluginsJson.plugins
  .map((entry) => {
    const exportName = toPluginExportName(entry.alias);

    return `  registerPlugin({ plugin: ${exportName}, ctx });`;
  })
  .join('\n');

const pluginsTs = `\
// generated/plugins.ts — AUTO-GENERATED, do not edit
// Generated by: bun run scripts/generate-tools.ts

import { registerPlugin } from '../src/core/registry';
import type { PluginContext } from '../src/core/plugin';
${imports}

export function registerPlugins(ctx: PluginContext): void {
${registrations}
}
`;

writeFileSync(PLUGINS_TS, pluginsTs, 'utf8');
console.log('[generate-tools] Generated generated/plugins.ts');

console.log('[generate-tools] Done.');
